### ISSUE TITLE
Mod dependency suggestion

### ISSUE THREAD

**Issue by CTNOriginals** [xjunko/Hikari#1]
Hello!
I'm the developer of the [CrossHair](https://thunderstore.io/c/lethal-company/p/CTNOriginals/CrossHair/) mod and came by your QoL mod here. I looked around a bit and noticed that you have taken a bit of inspiration from me, which you also mentioned in your readme.

Don't worry, I'm not here right now to take down anything you made.
At this point, the way you have implemented the CrossHair in this mod, its almost an exact replica of the way I did it originally but just with less features (which I understand).
I wanted to let you know that I hereby give you permission to use my mod as a direct dependency on this mod if you would like to do so. This way, you would get all the features without actually having to jump though those hoops your self.

This is just a suggestion on the given permission though, it is entirely up to you if you actually want to depend on it instead of what you have put in the mod.

Let me know what your stands is on this :)

**Comment by xjunko** [comment]
Ah, thanks for stopping by, and yes, the crosshair specifically were inspired, if not an exact replica, just like you said. Now, this mod was only intended for my friend's server, yknow, one of those "the boys" night where everyone is available, which is rare. It was never made for public use, and I understand your concern.

In case you haven't noticed, this mod hasn't be updated in a while, cuz again, it was made for my friends and no one has time to play anymore. And with that, I'll officially announce it here that I will be putting the mod down, and write out references to the mod that is being based on.

I do appreciate the permissions though, thanks!!! :D
